# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=25w41a
loader_version=0.17.3

deps.parchment.minecraft=1.21.8
deps.parchment.version=2025.07.20

# Mod Properties
mod_version=1.1.0
maven_group=games.enchanted.lightmapview
archives_base_name=eg_texture_viewer

# Dependencies
fabric_version=0.135.1+1.21.11